apiVersion: v1
kind: Service
metadata:
  name: euclid-cutout-service
  labels:
    app: euclid-cutout-service
spec:
  type: ClusterIP
  selector:
    app: euclid-cutout-service
  ports:
  - name: flask
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: mcp-sse
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None